#pragma once

#include <types.h>
#include <stddef.h>

#define SYSCALL_TYPE_PRINTF           0x01
#define SYSCALL_TYPE_VIRTUAL_ALLOC    0x02
#define SYSCALL_TYPE_STORAGE_ENUM     0x03
#define SYSCALL_TYPE_STORAGE_OPER     0x04
#define SYSCALL_TYPE_PARTITION_ENUM   0x05
#define SYSCALL_TYPE_STORAGE_IDENTIFY 0x06

typedef struct _SYSCALL_PRINTF
{
	QWORD       TYPE;
	const char *FMRT;
	va_list     VARG;
	DWORD       ATTR;
} SYSCALL_PRINTF;
typedef struct _SYSCALL_VIRTUAL_ALLOC
{
	QWORD  TYPE;
	QWORD  PROC;
	QWORD *ADDR;
	QWORD  SIZE;
	DWORD  ATYP;
} SYSCALL_VIRTUAL_ALLOC;
typedef struct _SYSCALL_STORAGE_ENUMERATE
{
	QWORD  TYPE;
	QWORD  CURR;
	QWORD *HNDL;
	DWORD *CONT;
} SYSCALL_STORAGE_ENUMERATE;
typedef struct _SYSCALL_STORAGE_OPERATION
{
	QWORD  TYPE;
	QWORD  HNDL;
	void  *ADDR;
	QWORD  LBAA;
	DWORD  CONT;
	DWORD  OPER;
} SYSCALL_STORAGE_OPERATION;
typedef struct _SYSCALL_PARTITION_ENUMERATE
{
	QWORD TYPE;
	QWORD HNDL;
	void *ADDR;
	QWORD CONT;
} SYSCALL_PARTITION_ENUMERATE;
typedef struct _SYSCALL_STORAGE_IDENTIFY
{
	QWORD TYPE;
	QWORD HNDL;
	char *MODN;
	char *SERN;
} SYSCALL_STORAGE_IDENTIFY;

void setup_system_call();