#ifndef SUPERNOVA_PCIE_H
#define SUPERNOVA_PCIE_H

#include <acpi/acpi.h>
#include <interrupt/interrupt.h>

#define PCIE_CAID_MSI  0x05
#define PCIE_CAID_MSIX 0x11

typedef struct _PCIE_SEGMENT_ADDRESS
{
	QWORD ECAM;
	WORD  PSEG;
	BYTE  SBUS;
	BYTE  EBUS;
	DWORD RSV0;
} PCIE_SEGMENT_ADDRESS;
#pragma pack(push, 4)
typedef struct _ACPI_MCFG
{
	ACPI_SDT_HEADER HEAD;
	DWORD RSV0[2];
	PCIE_SEGMENT_ADDRESS ECAM[];
} ACPI_MCFG;
#pragma pack(pop)
typedef struct _PCI_EXPRESS_DEVICE_CAPABILITY
{
	DWORD MPSS:3;
	/**
	 * Phantom Functions Supported - This field indicates the support for use of unclaimed Function Numbers
	 * to extend the number of outstanding transactions allowed by logically combining unclaimed Function
	 * Numbers (called Phantom Functions) with the Tag identifier (see § Section 2.2.6.2 for a description of
	 * Tag Extensions).
	 *
	 * For a PF of an SR-IOV Device with its VF Enable bit Set, the use of Phantom Function numbers is not
	 * permitted and this field must return Zero when read.
	 *
	 * For a PF of an SIOV Device with its SIOV Enabled bit Set, the use of Phantom Function numbers is not
	 * permitted and this field must return Zero when read.
	 *
	 * For VFs, this field is not supported and must be hardwired to Zero.
	 *
	 * For every Function in an ARI Device, this field must be hardwired to Zero.
	 *
	 * The remainder of this field description applies only to non-ARI Multi-Function Devices
	 * .
	 * This field indicates the number of most significant bits of the Function Number portion of Requester ID
	 * that are logically combined with the Tag identifier.
	 *
	 * Defined encodings are:
	 *
	 * - 00b No Function Number bits are used for Phantom Functions. Multi-Function Devices are
	 * permitted to implement up to 8 independent Functions.
	 * - 01b The most significant bit of the Function number in Requester ID is used for Phantom
	 * Functions; a Multi-Function Device is permitted to implement Functions 0-3. Functions 0,
	 * 1, 2, and 3 are permitted to use Function Numbers 4, 5, 6, and 7 respectively as Phantom
	 * Functions.
	 * - 10b The two most significant bits of Function Number in Requester ID are used for Phantom
	 * Functions; a Multi-Function Device is permitted to implement Functions 0-1. Function 0 is
	 * permitted to use Function Numbers 2, 4, and 6 for Phantom Functions. Function 1 is
	 * permitted to use Function Numbers 3, 5, and 7 as Phantom Functions.
	 * - 11b All 3 bits of Function Number in Requester ID used for Phantom Functions. The device
	 * must have a single Function 0 that is permitted to use all other Function Numbers as
	 * Phantom Functions.
	 *
	 * Note that Phantom Function support for the Function must be enabled by the Phantom Functions Enable
	 * field in the Device Control Register before the Function is permitted to use the Function Number field in
	 * the Requester ID for Phantom Functions.
	 */
	DWORD PFNS:2;
	/**
	 * Extended Tag Field Supported - This bit, in combination with the 10-Bit Tag Requester Supported bit and
	 * the 14-Bit Tag Requester Supported bit, indicates the maximum supported size of the Tag field as a
	 * Requester. This bit must be Set if the 10-Bit Tag Requester Supported bit or the 14-Bit Tag Requester
	 * Supported bit is Set.
	 *
	 * Defined encodings are:
	 * - 0b 5-bit Tag Requester capability supported
	 * - 1b 8-bit Tag Requester capability supported
	 *
	 * Note that 8-bit Tag field generation must be enabled by the Extended Tag Field Enable bit in the Device
	 * Control Register of the Requester Function before 8-bit Tags can be generated by the Requester. See
	 * § Section 2.2.6.2 for interactions with enabling the use of 10-Bit or 14-Bit Tags.
	 */
	DWORD ETFS:1;
	/**
	 * Endpoint L0s Acceptable Latency - This field indicates the acceptable total latency that an Endpoint can
	 * withstand due to the transition from L0s state to the L0 state. It is essentially an indirect measure of the
	 * Endpoint’s internal buffering.
	 *
	 * Power management software uses the reported L0s Acceptable Latency number to compare against the
	 * L0s exit latencies reported by all components comprising the data path from this Endpoint to the Root
	 * Complex Root Port to determine whether ASPM L0s entry can be used with no loss of performance.
	 *
	 * Defined encodings are:
	 * - 000b Maximum of 64 ns
	 * - 001b Maximum of 128 ns
	 * - 010b Maximum of 256 ns
	 * - 011b Maximum of 512 ns
	 * - 100b Maximum of 1 μs
	 * - 101b Maximum of 2 μs
	 * - 110b Maximum of 4 μs
	 * - 111b No limit
	 *
	 * For Functions other than Endpoints, this field is Reserved and must be hardwired to 000b.
	 */
	DWORD E0AL:3;
	/**
	 * Endpoint L1 Acceptable Latency - This field indicates the acceptable latency that an Endpoint can
	 * withstand due to the transition from L1 state to the L0 state. It is essentially an indirect measure of the
	 * Endpoint’s internal buffering.
	 *
	 * Power management software uses the reported L1 Acceptable Latency number to compare against the
	 * L1 Exit Latencies reported (see below) by all components comprising the data path from this Endpoint to
	 * the Root Complex Root Port to determine whether ASPM L1 entry can be used with no loss of
	 * performance.
	 *
	 * Defined encodings are:
	 * - 000b Maximum of 1 μs
	 * - 001b Maximum of 2 μs
	 * - 010b Maximum of 4 μs
	 * - 011b Maximum of 8 μs
	 * - 100b Maximum of 16 μs
	 * - 101b Maximum of 32 μs
	 * - 110b Maximum of 64 μs
	 * - 111b No limit
	 *
	 * For Functions other than Endpoints, this field is Reserved and must be hardwired to 000b.
	 */
	DWORD E1AL:3;
	/**
	 * Undefined - The value read from these bits are undefined. In previous versions of this specification, this
	 * bit was used to indicate that a Attention Button, Attention Indicator, or Power Indicator, is implemented
	 * on the adapter and electrically controlled by the component on the adapter. System software must
	 * ignore the value read from this bit. System software is permitted to write any value to this bit.
	 */
	DWORD UND1:3;
	/**
	 * Role-Based Error Reporting - When Set, this bit indicates that the Function implements Role-Based
	 * Error Reporting. This bit must be Set by all Functions conforming to [PCIe-1.1] or later revisions.
	 */
	DWORD RBEP:1;
	/**
	 * ERR_COR Subclass Capable - When Set, this bit indicates that the Function supports the ERR_COR
	 * Subclass field in ERR_COR Messages, allowing different subclasses to be distinguished. See § Section
	 * 2.2.8.3 .
	 *
	 * Downstream Ports that implement the System Firmware Intermediary (SFI) capability must Set this bit.
	 *
	 * Downstream Ports that implement Downstream Port Containment (DPC) are strongly encouraged to Set
	 * this bit.
	 */
	DWORD ECSC:1;
	/**
	 * Rx_MPS_Fixed – When Set, the Function's Rx_MPS_Limit is fixed with the value indicated by the
	 * Max_Payload_Size Supported field. Otherwise, the Rx_MPS_Limit is determined by the Max_Payload_Size
	 * field (the "MPS setting") in one or more Functions. See § Section 2.2.2 for important details regarding
	 * Multi-Function Devices. This bit MUST@FLIT be Set.
	 */
	DWORD RXMF:1;
	/**
	 * Captured Slot Power Limit Value (Upstream Ports only) - In combination with the Captured Slot Power
	 * Limit Scale value, specifies the upper limit on power available to the adapter.
	 *
	 * Power limit (in Watts) is calculated by multiplying the value in this field by the value in the Captured Slot
	 * Power Limit Scale field except when the Captured Slot Power Limit Scale field equals 00b (1.0x) and the
	 * Captured Slot Power Limit Value exceeds EFh, then alternative encodings are used (see § Section 7.5.3.9 ).
	 * This value is set by the Set_Slot_Power_Limit Message or hardwired to 00h (see § Section 6.9 ). The
	 * default value is 00h.
	 *
	 * For VFs, the field value when read is undefined.
	 */
	DWORD SPLV:8;
	/**
	 * Captured Slot Power Limit Scale (Upstream Ports only) - Specifies the scale used for the Slot Power Limit
	 * Value.
	 *
	 * Range of Values:
	 * - 00b 1.0x
	 * - 01b 0.1x
	 * - 10b 0.01x
	 * - 11b 0.001x
	 *
	 * This value is set by the Set_Slot_Power_Limit Message or hardwired to 00b (see § Section 6.9 ). The
	 * default value is 00b.
	 *
	 * For VFs, the field value when read is undefined.
	 */
	DWORD SPLS:2;
	/**
	 * Function Level Reset Capability - A value of 1b indicates the Function supports the optional Function
	 * Level Reset mechanism described in § Section 6.6.2 .
	 *
	 * This bit applies to Endpoints only. For all other Function types this bit must be hardwired to Zero.
	 *
	 * For PFs and VFs, the feature is mandatory and this bit must be Set.
	 */
	DWORD FRST:1;
	/**
	 * Mixed_MPS_Supported – When Set, the Function must have an implementation specific mechanism
	 * capable of supporting different MPS settings for different targets. This bit MUST@FLIT be Set if the
	 * Function supports P2P Memory Transactions and the Function's Max_Payload_Size Supported field
	 * indicates an MPS value greater than 512 bytes. If not mandatory, supporting Mixed MPS capability may
	 * still be beneficial if this Function does P2P with targets or over paths whose supported MPS is
	 * significantly less than this Function's supported MPS; e.g., 128 bytes vs. 512 bytes.
	 *
	 * The implementation specific mechanism must handle both Request and Completion TLPs, and is
	 * permitted to base its determination of P2P targets on Memory Space ranges, Bus Number ranges, or
	 * implementation specific means; e.g., data mover channels.
	 *
	 * For SR-IOV Devices, this field in each VF must have the same value its associated PF. If this field is Set, the
	 * implementation specific mechanism must use the same P2P target-specific MPS setting for each VF as its
	 * associated PF. This parallels the requirement for the Max_Payload_Size field in the Device Control
	 * Register.
	 */
	DWORD MMPS:1;
	/**
	 * TEE-IO Supported – When Set, this bit indicates that the Function implements the TEE-IO functionality
	 * as described by the TEE Device Interface Security Protocol (TDISP). See § Chapter 11. .
	 */
	DWORD TEIO:1;
	DWORD RSV1:1;
} PCI_EXPRESS_DEVICE_CAPABILITY;
typedef struct _PCI_EXPRESS_DEVICE_CONTROL
{
	/**
	 * Correctable Error Reporting Enable - This bit, in conjunction with other bits, controls sending ERR_COR
	 * Messages (see § Section 6.2.5 , § Section 6.2.6 , and § Section 6.2.11.2 for details). For a Multi-Function
	 * Device, this bit controls error reporting for each Function from point-of-view of the respective Function.
	 *
	 * For a Root Port, the reporting of correctable errors is internal to the root. No external ERR_COR Message
	 * is generated.
	 *
	 * An RCiEP that is not associated with a Root Complex Event Collector is permitted to hardwire this bit to
	 * 0b.
	 *
	 * Default value of this bit is 0b.
	 */
	DWORD CERE:1;
	/**
	 * Non-Fatal Error Reporting Enable - This bit, in conjunction with other bits, controls sending
	 * ERR_NONFATAL Messages (see § Section 6.2.5 and § Section 6.2.6 for details). For a Multi-Function
	 * Device, this bit controls error reporting for each Function from point-of-view of the respective Function.
	 * For a Root Port, the reporting of Non-fatal errors is internal to the root. No external ERR_NONFATAL
	 * Message is generated.
	 *
	 * An RCiEP that is not associated with a Root Complex Event Collector is permitted to hardwire this bit to
	 * 0b.
	 *
	 * Default value of this bit is 0b.
	 */
	DWORD NFRE:1;
	/**
	 * Fatal Error Reporting Enable - This bit, in conjunction with other bits, controls sending ERR_FATAL
	 * Messages (see § Section 6.2.5 and § Section 6.2.6 for details). For a Multi-Function Device, this bit
	 * controls error reporting for each Function from point-of-view of the respective Function.
	 *
	 * For a Root Port, the reporting of Fatal errors is internal to the root. No external ERR_FATAL Message is
	 * generated.
	 *
	 * An RCiEP that is not associated with a Root Complex Event Collector is permitted to hardwire this bit to
	 * 0b.
	 *
	 * Default value of this bit is 0b.
	 */
	DWORD FERE:1;
	/**
	 * Unsupported Request Reporting Enable - This bit, in conjunction with other bits, controls the signaling
	 * of Unsupported Request Errors by sending error Messages (see § Section 6.2.5 and § Section 6.2.6 for
	 * details). For a Multi-Function Device, this bit controls error reporting for each Function from
	 * point-of-view of the respective Function.
	 *
	 * An RCiEP that is not associated with a Root Complex Event Collector is permitted to hardwire this bit to
	 * 0b.
	 *
	 * Default value of this bit is 0b.
	 */
	DWORD URRE:1;
	/**
	 * Enable Relaxed Ordering - If this bit is Set, the Function is permitted to set the Relaxed Ordering bit in
	 * the Attributes field of transactions it initiates that do not require strong write ordering (see § Section
	 * 2.2.6.4 and § Section 2.4 ).
	 *
	 * A Function is permitted to hardwire this bit to 0b if it never sets the Relaxed Ordering attribute in
	 * transactions it initiates as a Requester.
	 *
	 * When not hardwired to 0b, the default value of this bit is 1b.
	 */
	DWORD RLOE:1;
	/**
	 * Max_Payload_Size - For specified cases, this field determines the maximum TLP payload size (the MPS
	 * setting) for the Function. Values permitted to be programmed are indicated by the Max_Payload_Size
	 * Supported field.
	 *
	 * As a Receiver, if the Rx_MPS_Fixed bit is Set, the Rx_MPS_Limit is fixed with the value indicated by the
	 * Max_Payload_Size Supported field. Otherwise, the Rx_MPS_Limit is determined by the MPS setting in one
	 * or more Functions. See § Section 2.2.2 for important details regarding Multi-Function Devices.
	 *
	 * As a Transmitter, the Function must not generate TLPs with payloads exceeding the MPS setting, with
	 * the exception of Functions in a Multi-Function Device, or Functions with implemention-specific
	 * mechanisms capable of supporting different MPS settings for different targets. See § Section 2.2.2 for
	 * important details.
	 *
	 * Defined encodings for this field are:
	 * - 000b 128 bytes MPS
	 * - 001b 256 bytes MPS
	 * - 010b 512 bytes MPS
	 * - 011b 1024 bytes MPS
	 * - 100b 2048 bytes MPS
	 * - 101b 4096 bytes MPS
	 * - 110b Reserved
	 * - 111b Reserved
	 *
	 * Functions that support only the 128-byte MPS are permitted to hardwire this field to 000b.
	 *
	 * System software is not required to program the same value for this field for all the Functions of a
	 * Multi-Function Device.
	 *
	 * Default value of this field is 000b.
	 */
	DWORD MPSZ:3;
	/**
	 * Extended Tag Field Enable - This bit, in combination with the 10-Bit Tag Requester Enable bit and the
	 * 14-Bit Tag Requester Enable bit, determines how many Tag field bits a Requester is permitted to use for
	 * non-UIO Requests. This bit is not applicable to a Requester when generating UIO Requests.
	 *
	 * The following applies when the 10-Bit Tag Requester Enable bit and the 14-Bit Tag Requester Enable bit are
	 * both Clear. If the Extended Tag Field Enable bit is Set, the Function is permitted to use an 8-bit Tag field as
	 * a Requester. If the bit is Clear, the Function is restricted to using a 5-bit Tag field.
	 *
	 * See § Section 2.2.6.2 for required behavior when one or both of these larger-Tag Requester Enable bits
	 * are Set.
	 *
	 * If software changes the value of the Extended Tag Field Enable bit while the Function has outstanding
	 * Non-Posted Requests, the result is undefined.
	 *
	 * Functions that do not implement this capability hardwire this bit to 0b.
	 * Default value of this bit is implementation specific.
	 */
	DWORD ETFE:1;
	/**
	 * Phantom Functions Enable - This bit determines how many outstanding Non-Posted Requests a
	 * Requester is permitted to generate. Non non-UIO Requests, the Extended Tag Field Enable, 10-Bit Tag
	 * Requester Enable, and 14-Bit Tag Requester Enable bits also apply. See § Section 2.2.6.2 for complete
	 * details.
	 *
	 * When Set, this bit enables a Function to use unclaimed Functions as Phantom Functions to extend the
	 * number of outstanding transaction identifiers. If the bit is Clear, the Function is not allowed to use
	 * Phantom Functions.
	 *
	 * Behavior is undefined when this bit is Set in Functions with enabled Shadow Functions.
	 *
	 * Software should not change the value of this bit while the Function has outstanding Non-Posted
	 * Requests; otherwise, the result is undefined.
	 *
	 * Functions that do not implement this capability hardwire this bit to 0b.
	 *
	 * Default value of this bit is 0b.
	 */
	DWORD PFNE:1;
	/**
	 * Aux Power PM Enable - When Set this bit, enables a Function to draw auxiliary power independent of
	 * PME Aux power. Functions that require auxiliary power on legacy operating systems should continue to
	 * indicate PME Aux power requirements. Auxiliary power is allocated as requested in the Aux_Current field
	 * of the Power Management Capabilities Register (PMC), independent of the PME_En bit in the Power
	 * Management Control/Status Register (PMCSR) (see § Chapter 5. ). For Multi-Function Devices, a
	 * component is allowed to draw auxiliary power if at least one of the Functions has this bit set.
	 *
	 * Note: Functions that consume auxiliary power must preserve the value of this sticky register when
	 * auxiliary power is available. In such Functions, this bit is not modified by Conventional Reset.
	 *
	 * Functions that do not implement this capability hardwire this bit to 0b.
	 *
	 * Additional Aux power is permitted to be allocated using the firmware based mechanism (see the
	 * Request D3Cold Aux Power Limit _DSM call as defined in [Firmware]).
	 *
	 * Additional Aux power is also permitted to be allocated by selecting a PM Sub State in the Power Limit
	 * mechanism (see § Section 7.8.1.3 ).
	 */
	DWORD APME:1;
	/**
	 * Enable No Snoop - If this bit is Set, the Function is permitted to Set the No Snoop bit in the Requester
	 * Attributes of transactions it initiates that do not require hardware enforced cache coherency (see
	 * § Section 2.2.6.5 ). Note that setting this bit to 1b should not cause a Function to Set the No Snoop
	 * attribute on all transactions that it initiates. Even when this bit is Set, a Function is only permitted to Set
	 * the No Snoop attribute on a transaction when it can guarantee that the address of the transaction is not
	 * stored in any cache in the system.
	 *
	 * This bit is permitted to be hardwired to 0b if a Function would never Set the No Snoop attribute in
	 * transactions it initiates.
	 *
	 * Default value of this bit is 1b.
	 */
	DWORD NSNE:1;
	/**
	 * Max_Read_Request_Size - This field sets the maximum Read Request size for the Function as a
	 * Requester. The Function must not generate Read Requests with a size exceeding the set value. Defined
	 * encodings for this field are:
	 * - 000b 128 bytes maximum Read Request size
	 * - 001b 256 bytes maximum Read Request size
	 * - 010b 512 bytes maximum Read Request size
	 * - 011b 1024 bytes maximum Read Request size
	 * - 100b 2048 bytes maximum Read Request size
	 * - 101b 4096 bytes maximum Read Request size
	 * - 110b Reserved
	 * - 111b Reserved
	 *
	 * Functions that do not generate Read Requests larger than 128 bytes and Functions that do not generate
	 * Read Requests on their own behalf are permitted to implement this field as Read Only (RO) with a value
	 * of 000b.
	 *
	 * Default value of this field is 010b.
	 */
	DWORD MRRS:3;
	/**
	 * Bridge Configuration Retry Enable / Initiate Function Level Reset - this bit has a different meaning
	 * based on Function type:
	 * - PCI Express to PCI/PCI-X Bridges:
	 * Bridge Configuration Retry Enable - When Set, this bit enables PCI Express to PCI/PCI-X
	 * bridges to return Request Retry Status (RRS) in response to Configuration Requests that target
	 * devices below the bridge. Refer to [PCIe-to-PCI-PCI-X-Bridge] for further details.
	 * Default value of this bit is 0b.
	 * - Endpoints with Function Level Reset Capability set to 1b:
	 * Initiate Function Level Reset - A write of 1b initiates Function Level Reset to the Function. The
	 * value read by software from this bit is always 0b.
	 * PFs and VFs must support FLR. Note: Performing FLR on a PF with an SR-IOV Extended
	 * Capability Clears Clears its VF Enable bit, which causes its VFs no longer to exist after the FLR
	 * completes. Performing FLR on a PF with a Scalable IOV Extended Capability clears its SDI
	 * Enabled bit, which causes its SDIs to be disabled after the FLR completes.
	 * - All others:
	 * Reserved - Must hardwire the bit to 0b.
	 */
	DWORD BCRE:1;
} PCI_EXPRESS_DEVICE_CONTROL;
typedef struct _PCI_EXPRESS_DEVICE_STATUS
{
	/**
	 * Correctable Error Detected - This bit indicates status of correctable errors detected. Errors are logged in
	 * this register regardless of whether error reporting is enabled or not in the Device Control Register. For a
	 * Multi-Function Device, each Function indicates status of errors as perceived by the respective Function.
	 *
	 * For Functions supporting Advanced Error Handling, errors are logged in this register regardless of the
	 * settings of the Correctable Error Mask register.
	 *
	 * Default value of this bit is 0b.
	 */
	WORD CORE:1;
	/**
	 * Non-Fatal Error Detected - This bit indicates status of Non-fatal errors detected. Errors are logged in this
	 * register regardless of whether error reporting is enabled or not in the Device Control Register. For a
	 * Multi-Function Device, each Function indicates status of errors as perceived by the respective Function.
	 *
	 * For Functions supporting Advanced Error Handling, errors are logged in this register regardless of the
	 * settings of the Uncorrectable Error Mask register.
	 *
	 * Default value of this bit is 0b.
	 */
	WORD NFAE:1;
	/**
	 * Fatal Error Detected - This bit indicates status of Fatal errors detected. Errors are logged in this register
	 * regardless of whether error reporting is enabled or not in the Device Control Register. For a
	 * Multi-Function Device, each Function indicates status of errors as perceived by the respective Function.
	 * For Functions supporting Advanced Error Handling, errors are logged in this register regardless of the
	 * settings of the Uncorrectable Error Mask register.
	 *
	 * Default value of this bit is 0b.
	 */
	WORD FATE:1;
	/**
	 * Unsupported Request Detected - This bit indicates that the Function received an Unsupported Request.
	 * Errors are logged in this register regardless of whether error reporting is enabled or not in the Device
	 * Control Register. For a Multi-Function Device, each Function indicates status of errors as perceived by
	 * the respective Function.
	 *
	 * Default value of this bit is 0b.
	 */
	WORD UNSR:1;
	/**
	 * AUX Power Detected - Functions that require auxiliary power report this bit as Set if auxiliary power is
	 * detected by the Function.
	 *
	 * For VFs, this bit is not supported and must be hardwired to Zero.
	 */
	WORD AUXP:1;
	/**
	 * Transactions Pending -
	 *
	 * *Endpoints:*
	 *
	 * When Set, this bit indicates that the Function is expecting one or more Completions. A Function reports
	 * this bit cleared only the Function is not expecting any Completions (All issued Non-Posted Requests and
	 * UIO Requests have completed or have been terminated by the Completion Timeout mechanism. This
	 * includes Requests that are issued by a host when taking ownership of a peer-to-peer Transaction.) This
	 * bit must also be cleared upon the completion of an FLR.
	 *
	 * Root and Switch Ports:
	 *
	 * When Set, this bit indicates that a Port has issued Non-Posted Requests or UIO Requests on its own
	 * behalf (using the Port’s own, or its Shadow Function’s, Requester ID) which have not been completed.
	 *
	 * The Port reports this bit cleared only when all such outstanding Non-Posted Requests or UIO Requests
	 * have completed or have been terminated by the Completion Timeout mechanism. Note that Root and
	 * Switch Ports implementing only the functionality required by this document do not issue Non-Posted
	 * Requests on their own behalf, and therefore are not subject to this case. Root and Switch Ports that do
	 * not issue Non-Posted Requests on their own behalf hardwire this bit to 0b.
	 */
	WORD PEND:1;
	/**
	 * Emergency Power Reduction Detected - This bit is Set when the Function is in the Emergency Power
	 * Reduction State. Whenever any condition is present that would cause the Emergency Power Reduction
	 * State to be entered, the Function remains in the Emergency Power Reduction State and writes to this bit
	 * have no effect. See § Section 6.24 for additional details.
	 *
	 * Multi-Function Devices associated with an Upstream Port must Set this bit in all Functions that support
	 * Emergency Power Reduction State.
	 *
	 * For VFs, this bit is not supported and must be hardwired to Zero.
	 *
	 * Except for VFs, this bit is RsvdZ if the Emergency Power Reduction Supported field is 00b (see § Section
	 * 7.5.3.15 ).
	 *
	 * This bit is RsvdZ in Functions that are not associated with an Upstream Port.
	 *
	 * Default value is 0b.
	 */
	WORD EMPR:1;
} PCI_EXPRESS_DEVICE_STATUS;
typedef struct _PCI_EXPRESS_CAPABILITY
{
	/**
	 * Capability ID [RO] - Indicates the PCI Express Capability structure. This field must return a Capability ID of
	 * 10h indicating that this is a PCI Express Capability structure.
	 */
	BYTE CAID;
	/**
	 * Next Capability Pointer [RO] - This field contains the offset to the next PCI Capability structure or 00h if no
	 * other items exist in the linked list of Capabilities.
	 */
	BYTE NEXT;
	/**
	 * Capability Version - Indicates PCI-SIG defined PCI Express Capability structure version number.
	 *
	 * A version of the specification that changes the PCI Express Capability structure in a way that is not
	 * otherwise identifiable (e.g., through a new Capability field) is permitted to increment this field. All such
	 * changes to the PCI Express Capability structure must be software-compatible. Software must check for
	 * Capability Version numbers that are greater than or equal to the highest number defined when the
	 * software is written, as Functions reporting any such Capability Version numbers will contain a PCI
	 * Express Capability structure that is compatible with that piece of software.
	 * Must be hardwired to 2h for Functions compliant to this specification.
	 */
	WORD CVER:4;
	/**
	 * Device/Port Type 179 - Indicates the specific type of this PCI Express Function. Note that different
	 * Functions in a Multi-Function Device can generally be of different types.
	 * Defined encodings for Functions that implement a Type 00h PCI Configuration Space header are:
	 * - 0000b PCI Express Endpoint
	 * - 0001b Legacy PCI Express Endpoint
	 * - 1001b RCiEP
	 * - 1010b Root Complex Event Collector
	 *
	 * Defined encodings for Functions that implement a Type 01h PCI Configuration Space header are:
	 * - 0100b Root Port of PCI Express Root Complex
	 * - 0101b Upstream Port of PCI Express Switch
	 * - 0110b Downstream Port of PCI Express Switch
	 * - 0111b PCI Express to PCI/PCI-X Bridge
	 * - 1000b PCI/PCI-X to PCI Express Bridge
	 *
	 * All other encodings are Reserved.
	 *
	 * Note that the different Endpoint types have notably different requirements in § Section 1.3.2 regarding
	 * I/O resources, Extended Configuration Space, and other capabilities.
	 */
	WORD DTYP:4;
	/**
	 * Slot Implemented - When Set, this bit indicates that the Link associated with this Port is connected to a
	 * slot (as compared to being connected to a system-integrated device or being disabled).
	 * This bit is valid for Downstream Ports. This bit is undefined for Upstream Ports.
	 */
	WORD SIMP:1;
	/**
	 * Interrupt Message Number - When MSI/MSI-X is implemented, this field indicates which MSI/MSI-X
	 * vector is used for the interrupt message generated in association with any of the status bits of this
	 * Capability structure. This vector is also used for:
	 * - Native PME Software Model (see § Section 6.1.6 and § Section 6.7.3.4 )
	 * - Link Activation (see § Section 5.5.6 )
	 * - Flit Error Counter Interrupts (see § Section 7.7.9.4 )
	 *
	 * For MSI, the value in this field indicates the offset between the base Message Data and the interrupt
	 * message that is generated. Hardware is required to update this field so that it is correct if the number of
	 * MSI Messages assigned to the Function changes when software writes to the Multiple Message Enable
	 * field in the Message Control Register for MSI.
	 *
	 * For MSI-X, the value in this field indicates which MSI-X Table entry is used to generate the interrupt
	 * message. The entry must be one of the first 32 entries even if the Function implements more than 32
	 * entries. For a given MSI-X implementation, the entry must remain constant.
	 *
	 * If both MSI and MSI-X are implemented, they are permitted to use different vectors, though software is
	 * permitted to enable only one mechanism at a time. If MSI-X is enabled, the value in this field must
	 * indicate the vector for MSI-X. If MSI is enabled or neither is enabled, the value in this field must indicate
	 * the vector for MSI. If software enables both MSI and MSI-X at the same time, the value in this field is
	 * undefined.
	 */
	WORD IMNU:5;
	WORD RSV0:1;
	/**
	 * Flit Mode Supported – When Set, indicates support for Flit Mode. Must be Set by all implementations
	 * that support Flit Mode. Must be Clear by implementations that do not support Flit Mode. See Flit Mode
	 * Supported bit.
	 */
	WORD FLIT:1;
	/**
	 * Max_Payload_Size Supported - This field indicates the maximum payload size that the Function can
	 * support for TLPs. This field MUST@FLIT indicate a minimum of 512 bytes.
	 *
	 * If the Rx_MPS_Fixed bit is Set, the Function's Rx_MPS_Limit is fixed with the value indicated by this
	 * (Max_Payload_Size Supported) field. Otherwise, the Rx_MPS_Limit is determined by the
	 * Max_Payload_Size field (the "MPS setting") in one or more Functions. See § Section 2.2.2 for important
	 * details regarding Multi-Function Devices.
	 * Defined encodings are:
	 * - 000b 128 bytes max payload size
	 * - 001b 256 bytes max payload size
	 * - 010b 512 bytes max payload size
	 * - 011b 1024 bytes max payload size
	 * - 100b 2048 bytes max payload size
	 * - 101b 4096 bytes max payload size
	 * - 110b Reserved
	 * - 111b Reserved
	 *
	 * The Functions of a Multi-Function Device are permitted to report different values for this field.
	 */
} PCI_EXPRESS_CAPABILITY;
typedef struct _PCI_CONFIGURATION_INTERRUPT
{
	BYTE line;
	BYTE pin;
	BYTE grant;
	BYTE latency;
} PCI_CONFIGURATION_INTERRUPT;
typedef struct _PCI_CONFIGURATION_SPACE
{
	WORD vendor;
	WORD device;
	WORD command;
	WORD status;
	DWORD revision:8;
	DWORD class:24;
	BYTE cache;
	BYTE latency;
	BYTE type;
	BYTE bist; // Built-In Self-Test
	DWORD address[6];
	DWORD cardbus;
	DWORD subsystem;
	DWORD expansion;
	BYTE capability;
	BYTE resvered0[7];
	PCI_CONFIGURATION_INTERRUPT interrupt;
} PCI_CONFIGURATION_SPACE;
typedef struct _PCI_EXPRESS_DEVICE
{
	DWORD offset:8;
	DWORD function:3;
	DWORD device:5;
	DWORD bus:8;
	DWORD reserve:8;
	volatile PCI_CONFIGURATION_SPACE *configuration;
} PCI_EXPRESS_DEVICE;

extern volatile ACPI_MCFG *volatile MCFG;

void setup_pcie_mcfg(ACPI_MCFG *mcfg);
void setup_pcie();
QWORD pcie_cfg_get_base_address(PCI_EXPRESS_DEVICE *device, DWORD addrIdx);
DWORD pcie_bar_cound(PCI_EXPRESS_DEVICE *device);
PCI_EXPRESS_CAPABILITY *__stdcall pcie_capability(PCI_EXPRESS_DEVICE *device, DWORD capa);
DWORD pcie_setup_interrupt(PCI_EXPRESS_DEVICE *device, void (*irq)(INTERRUPT_STACK *stack), BYTE intx);

#endif
