#pragma once

#ifndef SUPERNOVA_PE32X_H
#define SUPERNOVA_PE32X_H

#include <types.h>

#define IMAGE_NUMBEROF_DIRECTORY_ENTRIES    16

typedef struct _IMAGE_DOS_HEADER
{
	WORD A5D4; // MZ
	WORD CBLP; // Last page byte count
	WORD PCNT; // Page count
	WORD CRLC; // Relocation count
	WORD CHDR; // Header size (in 0x10)
	WORD MINM; // Min memory
	WORD MAXM; // Max memory
	WORD IISS; // Initial SS
	WORD IISP; // Initial SP
	WORD CSUM; // Checksum
	WORD IIIP; // Initial IP
	WORD IICS; // Initial CS
	WORD ARLC; // Relocation Table Address
	WORD OVNO; // Overlap Number
	WORD RSV0[4];
	WORD OEMX; // OEM ID
	WORD OEMI; // OEM INFO
	WORD RSV1[10];
	DWORD PEHO;// PE HEADER OFFSET
} IMAGE_DOS_HEADER;
typedef struct _IMAGE_FILE_HEADER
{
	WORD  MACH;
	WORD  SECT;
	DWORD TIME;
	DWORD SYMT;
	DWORD SYMN;
	WORD  OHSZ;
	WORD  CHAR;
} IMAGE_FILE_HEADER;
typedef struct _IMAGE_DATA_DIRECTORY
{
	DWORD ADDR;
	DWORD SIZE;
} IMAGE_DATA_DIRECTORY;
typedef struct _IMAGE_OPTIONAL_HEADER
{
	WORD  MAGC;
	BYTE  MAJV;
	BYTE  MINV;
	DWORD SCOD;
	DWORD IDAT;
	DWORD UDAT;
	DWORD ENTY;
	DWORD CODE;
	QWORD IMGE;
	DWORD SALN;
	DWORD FALN;
	DWORD OPSV;
	DWORD IMGV;
	DWORD SUBV;
	DWORD RSV0;
	DWORD SIMG;
	DWORD SHAD;
	DWORD CSUM;
	WORD  SUBS;
	WORD  CHAR;
	QWORD STCR;
	QWORD STCC;
	QWORD HAPR;
	QWORD HAPC;
	DWORD FLAG;
	DWORD DIRC;
	IMAGE_DATA_DIRECTORY DIRE[IMAGE_NUMBEROF_DIRECTORY_ENTRIES];
} IMAGE_OPTIONAL_HEADER;
typedef struct _IMAGE_NT_HEADERS
{
	DWORD SIGN;
	IMAGE_FILE_HEADER FILE;
	IMAGE_OPTIONAL_HEADER OPTI;
} IMAGE_NT_HEADERS;

#endif //SUPERNOVA_PE32X_H
