//
// Created by MeiVi on 2026/03/21.
//

#ifndef SUPERNOVA_XHC_TRB_H
#define SUPERNOVA_XHC_TRB_H

#include <types.h>
#include <driver/usb/usb_req.h>

#define XHCI_TRB_TYPE_NORMAL             1
#define XHCI_TRB_TYPE_SETUP_STAGE        2
#define XHCI_TRB_TYPE_DATA_STAGE         3
#define XHCI_TRB_TYPE_STATUS_STAGE       4
#define XHCI_TRB_TYPE_LINK               6
#define XHCI_TRB_TYPE_ENABLE_SLOT        9
#define XHCI_TRB_TYPE_DISABLE_SLOT       10
#define XHCI_TRB_TYPE_ADDRESS_DEVICE     11
#define XHCI_TRB_TYPE_CONFIGURE_ENDPOINT 12
#define XHCI_TRB_TYPE_EVALUATE_CONTEXT   13
#define XHCI_TRB_TYPE_TRANSFER_EVENT     32
#define XHCI_TRB_TYPE_COMMAND_COMPLETION 33
#define XHCI_TRB_TYPE_PORT_STATUS_CHANGE 34

#define XHCI_TRB_CTRL_CYCLE 1

/**
 * Indicates that the Completion Code field has not been updated by the
 * TRB producer.
 */
#define XHCI_CODE_INVALID                    0
// Indicates successful completion of the TRB operation.
#define XHCI_CODE_SUCCESS                    1
#define XHCI_CODE_DATA_BUFFER_ERROR          2
#define XHCI_CODE_BUBBLE_DETECTED_ERROR      3
#define XHCI_CODE_USB_TRANSACTION_ERROR      4
#define XHCI_CODE_TRB_ERROR                  5
/**
 * Asserted when a Stall condition (e.g., a Stall PID received from a device) is
 * detected for a TRB. Refer to section 4.10.2.1 for more information on
 * Stalls.
 *
 * This code also indicates that the USB device has an error that prevents it
 * from completing a command issued through a Control endpoint. Refer to
 * section 8.5.3.1 of the USB2 specification for more information.
 */
#define XHCI_CODE_STALL_ERROR                6
#define XHCI_CODE_RESOURCE_ERROR             7
#define XHCI_CODE_BANDWIDTH_ERROR            8
#define XHCI_CODE_NO_SLOT_AVAILABLE_ERROR    9
#define XHCI_CODE_INVALID_STREAM_TYPE_ERROR  10
#define XHCI_CODE_SLOT_NOT_ENABLED_ERROR     11
#define XHCI_CODE_ENDPOINT_NOT_ENABLED_ERROR 12
#define XHCI_CODE_SHORT_PACKET               13
#define XHCI_CODE_UNDERRUN                   14
#define XHCI_CODE_RING_OVERRUN               15

typedef struct _XHCI_TRB_GENERIC
{
	QWORD DATA;
	DWORD STAT;
	DWORD CTRL;
} XHCI_TRB_GENERIC;
typedef struct _XHCI_TRB_NORMAL
{
             	/**
	 * Data Buffer Pointer Hi and Lo. These fields represent the 64-bit address of the TRB data area
	 * for this transaction or 8 bytes of immediate data. The Immediate Data (IDT) control flag selects
	 * this option for each Normal TRB.
	 *
	 * The memory structure referenced by this physical memory pointer is allowed to begin on a byte
	 * address boundary. However, user may find other alignments, such as 64-byte or 128-byte
	 * alignments, to be more efficient and provide better performance.
	 */
	QWORD DATA;
	/**
	 * TRB Transfer Length. For an OUT, this field defines the number of data bytes the xHC shall
	 * send during the execution of this TRB. If the value of this field is ‘0’ when the xHC fetches this
	 * TRB, the xHC shall execute a zero-length transaction.
	 *
	 * Note: If a zero-length transfer is specified, the Data Buffer Pointer field is ignored by the xHC,
	 * irrespective of the state of the IDT flag. Refer to section 4.9.1 for more information on zero length Transfer TRB handling.
	 *
	 * For an IN, the value of the field identifies the size of the data buffer referenced by the Data
	 * Buffer Pointer, i.e. the number of bytes the host expects the endpoint to deliver.
	 *
	 * Valid values are 0 to 64K.
	 */
	DWORD TTRL:17;
	/**
	 * TD Size. This field provides an indicator of the number of packets remaining in the TD. Refer to
	 * section 4.10.2.4 for how this value is calculated.
	 */
	DWORD TDSZ:5;
	/**
	 * Interrupter Target. This field defines the index of the Interrupter that will receive events
	 * generated by this TRB. Valid values are between 0 and MaxIntrs-1.
	 */
	DWORD INTT:10;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of the Transfer ring.
	DWORD CYCL:1;
	/**
	 * Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the next TRB before
	 * saving the endpoint state. Refer to section 4.12.3 for more information.
	 */
	DWORD NEXT:1;
	/**
	 * Interrupt-on Short Packet (ISP). If this flag is ‘1’ and a Short Packet is encountered for this TRB
	 * (i.e., less than the amount specified in TRB Transfer Length), then a Transfer Event TRB shall be
	 * generated with its Completion Code set to Short Packet. The TRB Transfer Length field in the
	 * Transfer Event TRB shall reflect the residual number of bytes not transferred into the associated
	 * data buffer. In either case, when a Short Packet is encountered, the TRB shall be retired without
	 * error and the xHC shall advance to the next Transfer Descriptor (TD).
	 *
	 * Note that if the ISP and IOC flags are both ‘1’ and a Short Packet is detected, then only one
	 * Transfer Event TRB shall be queued to the Event Ring. Also refer to section 4.10.1.1.
	 */
	DWORD IOSP:1;
	/**
	 * No Snoop (NS). When set to ‘1’, the xHC is permitted to set the No Snoop bit in the Requester
	 * Attributes of the PCIe transactions it initiates if the PCIe configuration Enable No Snoop flag is
	 * also set. When cleared to ‘0’, the xHC is not permitted to set PCIe packet No Snoop Requester
	 * Attribute. Refer to section 4.18.1 for more information.
	 *
	 * NOTE: If software sets this bit, then it is responsible for maintaining cache consistency.
	 */
	DWORD NSNO:1;
	/**
	 * Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring. A
	 * Transfer Descriptor (TD) is defined as one or more TRBs. The Chain bit is used to identify the
	 * TRBs that comprise a TD. The Chain bit is always ‘0’ in the last TRB of a TD.
	 */
	DWORD CHAN:1;
	/**
	 * Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB completes,
	 * the Host Controller shall notify the system of the completion by placing an Transfer Event TRB
	 * on the Event ring and asserting an interrupt to the host at the next interrupt threshold. Note that
	 * the interrupt assertion may be blocked for the Transfer Event by BEI. Refer to sections 4.10.4
	 * and 4.17.5.
	 */
	DWORD IONC:1;
	/**
	 * Immediate Data (IDT). If this bit is set to ‘1’, it specifies that the Data Buffer Pointer field of this
	 * TRB contains data, not a pointer, and the Length field shall contain a value between ‘0’ and ‘8’ to
	 * indicate the number of valid bytes from offset 0 in the TRB that should be used as data.
	 *
	 * Note: If the IDT flag is set in one Transfer TRB of a TD, then it shall be the only Transfer TRB of
	 * the TD. An Event Data TRB may be included in the TD. Failure to follow this rule may result in
	 * undefined xHC operation.
	 *
	 * Note: IDT shall not be set (‘1’) for TRBs on endpoints that define a Max Packet Size < 8 bytes, or
	 * on IN endpoints.
	 */
	DWORD IDAT:1;
	DWORD RSV0:2;
	/**
	 * Block Event Interrupt (BEI). If this bit is set to ‘1’ and IOC = ‘1’, then the Transfer Event
	 * generated by IOC shall not assert an interrupt to the host at the next interrupt threshold. Refer
	 * to section 4.17.5.
	 */
	DWORD BEIT:1;
	// TRB Type. This shall be set to Normal TRB type. Refer to Table 6-91 for the definition of the valid Transfer TRB type IDs.
	DWORD TYPE:6;
	DWORD RSV1:16;
} XHCI_TRB_NORMAL;


typedef struct _XHCI_TRB_SETUP_STAGE
{
	USB_DEVICE_SETUP_DATA REQU;
	// TRB Transfer Length. Always 8
	DWORD TTRL:17;
	DWORD RSV0:5;
	/**
	 * Interrupter Target. This field defines the index of the Interrupter that will receive events
	 * generated by this TRB. Valid values are between 0 and MaxIntrs-1.
	 */
	DWORD INTT:10;
	// Cycle bit (C). This bit is used to mark the Enqueue point of a Transfer ring.
	DWORD CYCL:1;
	DWORD RSV1:4;
	/**
	 * Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB completes,
	 * the Host Controller shall notify the system of the completion by placing an Event TRB on the
	 * Event ring and sending an interrupt at the next interrupt threshold. Refer to section 4.10.4.
	 */
	DWORD IONC:1;
	/**
	 * Immediate Data (IDT). This bit shall be set to ‘1’ in a Setup Stage TRB. It specifies that the
	 * Parameter component of this TRB contains Setup Data.
	 */
	DWORD IDAT:1;
	DWORD RSV2:3;
	// TRB Type. This field is set to Setup Stage TRB type. Refer to Table 6-91 for the definition of the Type TRB IDs.
	DWORD TYPE:6;
	/**
	 * Transfer Type (TRT). This field indicates the type and direction of the control transfer.
	 * Value Definition
	 * - 0 No Data Stage
	 * - 1 Reserved
	 * - 2 OUT Data Stage
	 * - 3 IN Data Stage
	 *
	 * Refer to section 4.11.2.2 for more information on the use of TRT.
	 */
	DWORD TRTY:2;
	DWORD RSV3:14;
} XHCI_TRB_SETUP_STAGE;
typedef struct _XHCI_TRB_DATA_STAGE
{
	/**
	 * Data Buffer Pointer Hi and Lo. These fields represent the 64-bit address of the Data buffer area
	 * for this transaction.
	 *
	 * The memory structure referenced by this physical memory pointer is allowed to begin on a byte
	 * address boundary. However, user may find other alignments, such as 64-byte or 128-byte
	 * alignments, to be more efficient and provide better performance.
	 */
	QWORD DATA;
	/**
	 * TRB Transfer Length. For an OUT, this field is the number of data bytes the xHC will send
	 * during the execution of this TRB.
	 *
	 * For an IN, the initial value of the field identifies the size of the data buffer referenced by the Data
	 * Buffer Pointer, i.e. the number of bytes the host expects the endpoint to deliver.
	 * Valid values are 1 to 64K.
	 */
	DWORD TTRL:17;
	/**
	 * TD Size. This field provides an indicator of the number of packets remaining in the TD. Refer to
	 * section 4.11.2.4 for how this value is calculated.
	 */
	DWORD TDSZ:5;
	/**
	 * Interrupter Target. This field defines the index of the Interrupter that will receive events
	 * generated by this TRB. Valid values are between 0 and MaxIntrs-1.
	 */
	DWORD INTT:10;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of the Transfer ring.
	DWORD CYCL:1;
	/**
	 * Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the next TRB before
	 * saving the endpoint state. Refer to section 4.12.3 for more information.
	 */
	DWORD ENXT:1;
	/**
	 * Interrupt-on Short Packet (ISP). If this flag is ‘1’ and a Short Packet is encountered for this TRB
	 * (i.e., less than the amount specified in TRB Transfer Length), then a Transfer Event TRB shall be
	 * generated with its Completion Code set to Short Packet. The TRB Transfer Length field in the
	 * Transfer Event TRB shall reflect the residual number of bytes not transferred into the associated
	 * data buffer. In either case, when a Short Packet is encountered, the TRB shall be retired without
	 * error and the xHC shall advance to the Status Stage TD.
	 *
	 * Note: if the ISP and IOC flags are both ‘1’ and a Short Packet is detected, then only one Transfer
	 * Event TRB shall be queued to the Event Ring. Also refer to section 4.10.1.1.
	 */
	DWORD IOSP:1;
	/**
	 * No Snoop (NS). When set to ‘1’, the xHC is permitted to set the No Snoop bit in the Requester
	 * Attributes of the PCIe transactions it initiates if the PCIe configuration Enable No Snoop flag is
	 * also set. When cleared to ‘0’, the xHC is not permitted to set PCIe packet No Snoop Requester
	 * Attribute. Refer to section 4.18.1 for more information.
	 *
	 * NOTE: If software sets this bit, then it is responsible for maintaining cache consistency.
	 */
	DWORD NSNO:1;
	/**
	 * Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring. A Data
	 * Stage TD is defined as a Data Stage TRB followed by zero or more Normal TRBs. The Chain bit is
	 * used to identify a multi-TRB Data Stage TD. The Chain bit is always ‘0’ in the last TRB of a Data
	 * Stage TD.
	 */
	DWORD CHAN:1;
	/**
	 * Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB completes,
	 * the Host Controller shall notify the system of the completion by placing an Event TRB on the
	 * Event ring and asserting an interrupt to the host at the next interrupt threshold. Refer to section
	 * 4.10.4.
	 */
	DWORD IONC:1;
	/**
	 * Immediate Data (IDT). If this bit is set to ‘1’, it specifies that the Data Buffer Pointer field of this
	 * TRB contains data, not a pointer. If IDT = ‘1’, the Length field shall contain a value between 1 and
	 * 8 to indicate the number of valid bytes from offset 0 in the TRB that should be used as data.
	 *
	 * Note: If the IDT flag is set in one Data Stage TRB of a TD, then it shall be the only Transfer TRB of
	 * the TD. An Event Data TRB may also be included in the TD. Failure to follow this rule may result
	 * in undefined xHC operation.
	 */
	DWORD IDAT:1;
	DWORD RSV0:3;
	// TRB Type. This shall be set to Data Stage TRB type. Refer to Table 6-91 for the definition of the valid Transfer TRB type IDs.
	DWORD TYPE:6;
	/**
	 * Direction (DIR). This bit indicates the direction of the data transfer as defined in the Data State
	 * TRB Direction column of Table 7. If cleared to ‘0’, the data stage transfer direction is OUT (Write
	 * Data). If set to ‘1’, the data stage transfer direction is IN (Read Data). Refer to section 4.11.2.2 for
	 * more information on the use of DIR.
	 */
	DWORD DIRE:1;
	DWORD RSV1:15;
} XHCI_TRB_DATA_STAGE;
typedef struct _XHCI_TRB_STATUS_STAGE
{
	QWORD RSV0;
	DWORD RSV1:22;
	/**
	 * Interrupter Target. This field defines the index of the Interrupter that will receive events
	 * generated by this TRB. Valid values are between 0 and MaxIntrs-1.
	 */
	DWORD INTT:10;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of the Transfer ring.
	DWORD CYCL:1;
	/**
	 * Evaluate Next TRB (ENT). If this flag is ‘1’ the xHC shall fetch and evaluate the next TRB before
	 * saving the endpoint state. Refer to section 4.12.3 for more information.
	 */
	DWORD ENXT:1;
	DWORD RSV2:2;
	/**
	 * Chain bit (CH). Set to ‘1’ by software to associate this TRB with the next TRB on the Ring. A Data
	 * Stage TD is defined as a Data Stage TRB followed by zero or more Normal TRBs. The Chain bit is
	 * used to identify a multi-TRB Data Stage TD. The Chain bit is always ‘0’ in the last TRB of a Data
	 * Stage TD.
	 */
	DWORD CHAN:1;
	/**
	 * Interrupt On Completion (IOC). If this bit is set to ‘1’, it specifies that when this TRB completes,
	 * the Host Controller shall notify the system of the completion by placing an Event TRB on the
	 * Event ring and asserting an interrupt to the host at the next interrupt threshold. Refer to section
	 * 4.10.4.
	 */
	DWORD IONC:1;
	DWORD RSV3:4;
	// TRB Type. This field shall be set to Status Stage TRB type. Refer to Table 6-91 for the definition of the valid Transfer TRB type IDs.
	DWORD TYPE:6;
	/**
	 * Direction (DIR). This bit indicates the direction of the data transfer as defined in the Data State
	 * TRB Direction column of Table 7. If cleared to ‘0’, the data stage transfer direction is OUT (Write
	 * Data). If set to ‘1’, the data stage transfer direction is IN (Read Data). Refer to section 4.11.2.2 for
	 * more information on the use of DIR.
	 */
	DWORD DIRE:1;
	DWORD RSV4:15;
} XHCI_TRB_STATUS_STAGE;
typedef struct _XHCI_TRB_LINK
{
	QWORD RING; // Ring Segment Pointer, should on a 16-byte boundry
	DWORD RSV0:22;
	DWORD INTT:10; // Interrupter Target
	DWORD CYCL:1; // Cycle bit
	DWORD CYCT:1; // Cycle Toggle
	DWORD RSV1:2;
	DWORD CHAN:1; // Chain bit
	DWORD IONC:1; // Interrupt On Completion
	DWORD RSV2:4;
	DWORD TYPE:6; // TRB Type
	DWORD RSV3:16;
} XHCI_TRB_LINK;
typedef struct _XHCI_TRB_ENABLE_SLOT
{
	QWORD RSV0;
	DWORD RSV1;
	/**
	 * Cycle bit (C). This bit is used to mark the Enqueue Pointer of a Command Ring.
	 */
	DWORD CYCL:1;
	DWORD RSV2:9;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Enable Slot Command TRB type ID.
	 */
	DWORD TYPE:6;
	/**
	 * Slot Type. This field identifies the type of Slot that will be enabled by this command. Refer to
	 * Table 7-9 for more information on the usage of Slot Type.
	 */
	DWORD SLOT:5;
	DWORD RSV3:11;
} XHCI_TRB_ENABLE_SLOT;
typedef struct _XHCI_TRB_DISABLE_SLOT
{
	QWORD RSV0;
	DWORD RSV1;
	/**
	 * Cycle bit (C). This bit is used to mark the Enqueue Pointer of a Command Ring.
	 */
	DWORD CYCL:1;
	DWORD RSV2:9;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Disable Slot Command TRB type ID.
	 */
	DWORD TYPE:6;
	DWORD RSV3:8;
	// Slot ID. The ID of the Device Slot to disable.
	DWORD SLOT:8;
} XHCI_TRB_DISABLE_SLOT;
typedef struct _XHCI_TRB_ADDRESS_DEVICE
{
	/**
	 * Input Context Pointer Hi and Lo. This field represents the high order bits of the 64-bit base
	 * address of the Input Context data structure associated with this command. Refer to section 6.2.5
	 * for more information on the Input Context data structure.
	 *
	 * The memory structure referenced by this physical memory pointer shall be aligned on a 16-byte
	 * address boundary.
	 */
	QWORD CTXT;
	DWORD RSV0;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of a Command Ring.
	DWORD CYCL:1;
	DWORD RSV1:8;
	/**
	 * Block Set Address Request (BSR). When this flag is set to ‘0’ the Address Device Command shall
	 * generate a USB SET_ADDRESS request to the device. When this flag is set to ‘1’ the Address
	 * Device Command shall not generate a USB SET_ADDRESS request. Refer to section 4.6.5 for
	 * more information on the use of this flag.
	 */
	DWORD BSAR:1;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Address Device Command TRB type ID.
	 */
	DWORD TYPE:6;
	DWORD RSV2:8;
	// Slot ID. The ID of the Device Slot that is the target of this command.
	DWORD SLOT:8;
} XHCI_TRB_ADDRESS_DEVICE;
typedef struct _XHCI_TRB_CONFIGURE_ENDPOINT
{
	/**
	 * Input Context Pointer Hi and Lo. This field represents the high order bits of the 64-bit base
	 * address of the Input Context data structure associated with this event. Refer to section 6.2.5 for
	 * more information on the Input Context data structure.
	 * The memory structure referenced by this physical memory pointer shall be aligned on a 16-byte
	 * address boundary.
	 */
	QWORD CTXT;
	DWORD RSV0;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of a Command Ring
	WORD  CYCL:1;
	WORD  RSV1:8;
	/**
	 * Deconfigure (DC). Set to ‘1’ by software to “deconfigure” the Device Slot. If the DC flag = ‘1’, the
	 * Input Context Pointer field is ignored by the xHC.
	 */
	WORD  DCNF:1;
	// TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the  Configure Endpoint Command TRB type ID.
	WORD  TYPE:6;
	BYTE  RSV2;
	// Slot ID. The ID of the Device Slot that is the target of this command.
	BYTE  SLOT;
} XHCI_TRB_CONFIGURE_ENDPOINT;
typedef struct _XHCI_TRB_EVALUATE_CONTEXT
{
	/**
	 * Input Context Pointer Hi and Lo. This field represents the high order bits of the 64-bit base
	 * address of the Input Context data structure associated with this command. Refer to section 6.2.5
	 * for more information on the Input Context data structure.
	 *
	 * The memory structure referenced by this physical memory pointer shall be aligned on a 16-byte
	 * address boundary.
	 */
	QWORD CTXT;
	DWORD RSV0;
	// Cycle bit (C). This bit is used to mark the Enqueue Pointer of a Command Ring.
	DWORD CYCL:1;
	DWORD RSV1:8;
	/**
	 * Block Set Address Request (BSR). When this flag is set to ‘0’ the Address Device Command shall
	 * generate a USB SET_ADDRESS request to the device. When this flag is set to ‘1’ the Address
	 * Device Command shall not generate a USB SET_ADDRESS request. Refer to section 4.6.5 for
	 * more information on the use of this flag.
	 *
	 * Not used in Evaluate Context command
	 */
	DWORD BSAR:1;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Evaluate Context Command TRB type ID.
	 */
	DWORD TYPE:6;
	DWORD RSV2:8;
	// Slot ID. The ID of the Device Slot that is the target of this command.
	DWORD SLOT:8;
} XHCI_TRB_EVALUATE_CONTEXT;
typedef struct _XHCI_TRB_TRANSFER_EVENT
{
	/**
	 * TRB Pointer Hi and Lo. This field represents the 64-bit address of the TRB that generated this
	 * event or 64 bits of Event Data if the ED flag is ‘1’.
	 *
	 * If a TRB memory structure is referenced by this field (ED = ‘0’), then it shall be physical memory
	 * pointer aligned on a 16-byte boundary, i.e. bits 0 through 3 of the address are ‘0’.
	 */
	QWORD XFER;
	/**
	 * TRB Transfer Length. This field shall reflect the residual number of bytes not transferred.
	 *
	 * For an OUT, this field shall indicate the value of the Length field of the Transfer TRB, minus the
	 * data bytes that were successfully transmitted. A successful OUT transfer shall return a Length of
	 * ‘0’.
	 *
	 * For an IN, this field shall indicate the value of the TRB Transfer Length field of the Transfer TRB,
	 * minus the data bytes that were successfully received. If the device terminates the receive
	 * transfer with a Short Packet, then this field shall indicate the difference between the expected
	 * transfer size (defined by the Transfer TRB) and the actual number of bytes received. If the
	 * receive transfer completed with an error, then this field shall indicate the difference between
	 * the expected transfer size and the number of bytes successfully received.
	 *
	 * If the Event Data flag is ‘0’ the legal range of values is 0 to 10000h. If the Event Data flag is ‘1’ or
	 * the Condition Code is Stopped - Short Packet, then this field shall be set to the value of the
	 * Event Data Transfer Length Accumulator (EDTLA). Refer to section 4.11.5.2 for a description of
	 * EDTLA.
	 */
	DWORD TTRL:24;
	/**
	 * Completion Code. This field encodes the completion status that can be identified by a TRB.
	 & Refer to section 6.4.5 for an enumerated list of possible error conditions.
	 */
	DWORD CCOD:8;
	// Cycle bit (C). This bit is used to mark the Dequeue Pointer of an Event Ring.
	DWORD CYCL:1;
	DWORD RSV0:1;
	/**
	 * Event Data (ED). When set to ‘1’, the event was generated by an Event Data TRB and the
	 * Parameter Component (TRB Pointer field) contains a 64-bit value provided by the Event Data
	 * TRB. If cleared to ‘0’, the Parameter Component (TRB Pointer field) contains a pointer to the TRB
	 * that generated this event. Refer to section 4.11.5.2 for more information.
	 */
	DWORD EDAT:1;
	DWORD RSV1:7;
	// TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the Transfer Event TRB type ID.
	DWORD TYPE:6;
	/**
	 * Endpoint ID. The ID of the Endpoint that generated the event. This value is used as an index in
	 * the Device Context to select the Endpoint Context associated with this event.
	 */
	DWORD EPID:5;
	DWORD RSV2:3;
	/**
	 * Slot ID. The ID of the Device Slot that generated the event. This is value is used as an index in
	 * the Device Context Base Address Array to select the Device Context of the source device.
	 */
	DWORD SLOT:8;
} XHCI_TRB_TRANSFER_EVENT;
typedef struct _XHCI_TRB_COMMAND_COMPLETION
{
	/**
	 * Command TRB Pointer Hi and Lo. This field represents the high order bits of the 64-bit address
	 * of the Command TRB that generated this event. Note that this field is not valid for some
	 * Completion Code values. Refer to Table 6-90 for specific cases.
	 *
	 * The memory structure referenced by this physical memory pointer shall be aligned on a 16-byte
	 * address boundary.
	 */
	QWORD CMMD;
	/**
	 * Command Completion Parameter. This field may optionally be set by a command. Refer to
	 * section 4.6.6.1 for specific usage. If a command does not utilize this field it shall be treated as
	 * RsvdZ.
	 */
	DWORD PARM:24;
	/**
	 * Completion Code. This field encodes the completion status of the command that generated the
	 * event. Refer to the respective command definition for a list of the possible Completion Codes
	 * associated with the command. Refer to section 6.4.5 for an enumerated list of possible error
	 * conditions.
	 */
	DWORD CCOD:8;
	// Cycle bit (C). This bit is used to mark the Dequeue Pointer of an Event Ring.
	WORD  CYCL:1;
	WORD  RSV0:9;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Command Completion Event TRB type ID.
	 */
	WORD  TYPE:6;
	/**
	 * VF ID. The ID of the Virtual Function that generated the event. Note that this field is valid only if
	 * Virtual Functions are enabled. If they are not enabled this field shall be cleared to ‘0’.
	 */
	BYTE  VFID;
	/**
	 * Slot ID. The Slot ID field shall be updated by the xHC to reflect the slot associated with the
	 * command that generated the event, with the following exceptions:
	 *
	 * - The Slot ID shall be cleared to ‘0’ for No Op, Set Latency Tolerance Value, Get Port Bandwidth,
	 * and Force Event Commands.
	 *
	 * - The Slot ID shall be set to the ID of the newly allocated Device Slot for the Enable Slot
	 * Command.
	 *
	 * - The value of Slot ID shall be vendor defined when generated by a vendor defined command.
	 * 
	 * This value is used as an index in the Device Context Base Address Array to select the Device
	 * Context of the source device. If this Event is due to a Host Controller Command, then this field
	 * shall be cleared to ‘0’.
	 */
	BYTE  SLID;
} XHCI_TRB_COMMAND_COMPLETION;
typedef struct _XHCI_TRB_PORT_STATUS_CHANGE
{
	WORD  RSV0;
	BYTE  RSV1;
	// Port ID. The Port Number of the Root Hub Port that generated this event.
	BYTE  PRID;
	DWORD RSV2;
	WORD  RSV3;
	BYTE  RSV4;
	/**
	 * Completion Code. This field encodes the completion status that can be identified by a TRB. The
	 * Completion Code field shall be set to Success.
	 */
	BYTE  CCOD;
	// Cycle bit (C). This bit is used to mark the Dequeue Pointer of an Event Ring.
	WORD  CYCL:1;
	WORD  RSV5:9;
	/**
	 * TRB Type. This field identifies the type of the TRB. Refer to Table 6-91 for the definition of the
	 * Port Status Change Event TRB type ID.
	 */
	WORD  TYPE:6;
	WORD  RSV6;
} XHCI_TRB_PORT_STATUS_CHANGE;

#endif //SUPERNOVA_XHC_TRB_H
